name: CI

on:
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C environment
        run: sudo apt-get update && sudo apt-get install -y build-essential libbsd-dev python3 valgrind && python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette

      - name: Build and test the project
        run: make fulltest
